<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Identity\Register\ConfirmationEmail.html" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Identity\Register\ConfirmationEmail.html" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Levara.Domain\Levara.Domain.csproj" />
    <ProjectReference Include="..\Levara.Domain\Levara.Domain.csproj" />
    <ProjectReference Include="..\Levara.Shared\Levara.Shared.csproj" />
  </ItemGroup>

</Project>
