<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Emails\Templates\PasswordReset.html" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Emails\Templates\PasswordReset.html" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentEmail.Smtp" Version="3.0.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Levara.Domain\Levara.Domain.csproj" />
  </ItemGroup>

</Project>
