name: Deploy to AWS Lambda

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout del código
    - name: Checkout Code
      uses: actions/checkout@v3

    # Configurar .NET Core
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' # Cambia según tu versión de .NET Core

    # Restaurar dependencias
    - name: Restore dependencies
      run: dotnet restore Levara.WebApi/Levara.WebApi.csproj

    # Construir el proyecto
    - name: Build
      run: dotnet build Levara.WebApi/Levara.WebApi.csproj --configuration Release --no-restore

    # Publicar el proyecto
    - name: Publish
      run: dotnet publish Levara.WebApi/Levara.WebApi.csproj -c Release -o output

    # Empaquetar para AWS Lambda
    - name: Package for AWS Lambda
      run: |
        cd output
        zip -r ../Levara.WebApi.zip .

    # Desplegar a AWS Lambda usando AWS CLI
    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code \
          --function-name LevaraFuntions \
          --zip-file fileb://Levara.WebApi.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1 # Cambia según tu región
